"use client";

import { useQuery } from "@tanstack/react-query";
import { Activity, BookOpenCheck, Database, RefreshCw, ShieldCheck, UsersRound } from "lucide-react";
import { PageHeader } from "@/components/states/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { KnowledgeUpload } from "@/features/knowledge/knowledge-upload";
import { aiApi, authApi, coreApi, getAccessToken, queryKeys } from "@/lib/api/client";
import { titleCase } from "@/lib/utils";

export function AdminPage() {
  const core = useQuery({ queryKey: queryKeys.coreHealth, queryFn: coreApi.health, refetchInterval: 20_000 });
  const ai = useQuery({ queryKey: queryKeys.aiHealth, queryFn: aiApi.health, refetchInterval: 20_000 });
  const ready = useQuery({ queryKey: queryKeys.aiReadiness, queryFn: aiApi.readiness, refetchInterval: 20_000 });
  const documents = useQuery({ queryKey: queryKeys.knowledgeDocuments, queryFn: coreApi.knowledgeDocuments });
  const dashboard = useQuery({ queryKey: queryKeys.dashboard, queryFn: coreApi.dashboard });
  const users = useQuery({ queryKey: ["admin", "users"], queryFn: authApi.users, enabled: Boolean(getAccessToken()), retry: false });
  const refresh = () => { void core.refetch(); void ai.refetch(); void ready.refetch(); void documents.refetch(); void dashboard.refetch(); void users.refetch(); };
  const authRequired = core.data?.data.auth_required ?? false;
  return <div className="space-y-7"><PageHeader eyebrow="Platform operations" title="Admin" description="Live service readiness, database mode, security posture, users, operational metrics, and approved knowledge ingestion." actions={<Button variant="secondary" onClick={refresh}><RefreshCw />Refresh</Button>} />
    <div className={`flex gap-3 rounded-2xl border p-4 ${authRequired ? "border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300" : "border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-300"}`}><ShieldCheck className="mt-0.5 size-5 shrink-0" /><div><p className="text-sm font-semibold">{authRequired ? "Server-side authentication is enforced" : "Development authentication bypass is active"}</p><p className="mt-1 text-xs leading-5">JWT authentication, role checks, request validation, internal-service authentication, and rate limiting are implemented. Production startup rejects an authentication bypass or missing secrets.</p></div></div>
    <section><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">System health</h2><Badge variant={core.data && ai.data && ready.data ? "success" : "warning"}>Live service checks</Badge></div><div className="grid gap-4 md:grid-cols-3">{core.isLoading ? <Skeleton className="h-36 rounded-2xl" /> : <HealthCard icon={Database} label="Core sales API" status={core.data?.data.status ?? "unavailable"} detail={core.data ? `${core.data.data.database} · ${core.data.data.env}` : core.error?.message} />}{ai.isLoading ? <Skeleton className="h-36 rounded-2xl" /> : <HealthCard icon={Activity} label={ai.data?.service ?? "AI copilot API"} status={ai.data?.status ?? "unavailable"} detail={ai.data ? `${ai.data.environment} · v${ai.data.version}` : ai.error?.message} />}{ready.isLoading ? <Skeleton className="h-36 rounded-2xl" /> : <HealthCard icon={BookOpenCheck} label="Knowledge retrieval" status={ready.data?.dependencies.chroma?.status ?? ready.data?.status ?? "unavailable"} detail={ready.data?.dependencies.chroma?.detail ?? ready.error?.message} />}</div></section>
    <div className="grid gap-4 md:grid-cols-3"><Metric label="Active calls" value={dashboard.data?.data.metrics.active_calls ?? 0} /><Metric label="Pending follow-ups" value={dashboard.data?.data.metrics.pending_follow_ups ?? 0} /><Metric label="AI suggestion usage" value={`${(dashboard.data?.data.metrics.ai_suggestion_usage_rate ?? 0).toFixed(1)}%`} /></div>
    <div className="grid items-start gap-5 xl:grid-cols-[1fr_380px]"><Card className="p-5"><h2 className="text-sm font-semibold">Knowledge management</h2><p className="mt-1 text-xs leading-5 text-slate-500">Index a versioned approved document into Chroma and register it in the core catalog.</p><div className="mt-5"><KnowledgeUpload /></div></Card><Card className="p-5"><div className="flex items-center justify-between"><p className="flex items-center gap-2 text-sm font-semibold"><UsersRound className="size-4 text-blue-600" />Authorized users</p><Badge>{users.data?.length ?? 0}</Badge></div><div className="mt-4 space-y-3">{users.data?.map((user) => <div key={user.id} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800/50"><p className="text-xs font-medium">{user.display_name}</p><p className="mt-1 text-[10px] text-slate-400">{user.email} · {titleCase(user.role)}</p></div>)}{!getAccessToken() ? <p className="text-xs leading-5 text-slate-500">User administration is available to signed-in administrators when authentication is enabled.</p> : users.isError ? <p className="text-xs leading-5 text-amber-600">This identity is not authorized to list users.</p> : null}</div></Card></div>
    <Card className="p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Persistent knowledge catalog</h2><Badge>{documents.data?.data.length ?? 0} uploaded</Badge></div><p className="mt-2 text-xs leading-5 text-slate-500">Approved database products are synchronized into retrieval on startup; uploaded policy documents are tracked here with version and chunk counts.</p></Card>
  </div>;
}

function HealthCard({ icon: Icon, label, status, detail }: { icon: typeof Activity; label: string; status: string; detail?: string }) { const healthy = status === "healthy"; return <Card className="p-4"><div className="flex items-start justify-between"><div className="grid size-9 place-items-center rounded-xl bg-slate-100 text-slate-500 dark:bg-slate-800"><Icon className="size-4" /></div><Badge variant={healthy ? "success" : status === "degraded" ? "warning" : "danger"}>{titleCase(status)}</Badge></div><p className="mt-4 text-sm font-semibold">{label}</p><p className="mt-1 truncate text-[11px] text-slate-400">{detail ?? "No details returned"}</p></Card>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <Card className="p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></Card>; }
