"use client";

import { CalendarClock, LockKeyhole, Mail, MapPin, Phone, ShieldCheck, ShoppingBag, Tag, UserRound } from "lucide-react";
import Image from "next/image";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Sheet, SheetContent } from "@/components/ui/sheet";
import type { CoreCustomer } from "@/lib/api/contracts";
import { getInitials, titleCase } from "@/lib/utils";

export function CustomerDrawer({ customer, open, onOpenChange }: { customer: CoreCustomer | null; open: boolean; onOpenChange: (open: boolean) => void; requestedId: string }) {
  if (!customer) return null;
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="w-[min(96vw,620px)]" title={`${customer.name} profile`}>
    <div className="pr-10"><div className="flex items-center gap-4">{customer.photo ? <Image src={customer.photo} alt="" width={56} height={56} unoptimized className="size-14 rounded-2xl object-cover" /> : <div className="grid size-14 place-items-center rounded-2xl bg-blue-50 text-base font-semibold text-blue-700 dark:bg-blue-950 dark:text-blue-300">{getInitials(customer.name)}</div>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-xl font-semibold tracking-tight">{customer.name}</h2><Badge variant={customer.kycStatus === "verified" ? "success" : "warning"}><ShieldCheck className="size-3" />KYC {titleCase(customer.kycStatus)}</Badge><Badge variant="primary">Lead {customer.leadScore}</Badge></div><p className="mt-1 break-all text-xs text-slate-400">{customer.id} · {titleCase(customer.stage)}</p></div></div>
      <Separator className="my-5" /><div className="grid gap-3 sm:grid-cols-2"><ProfileField icon={Phone} label="Phone" value={customer.phone} /><ProfileField icon={Mail} label="Email" value={customer.email ?? "Not provided"} /><ProfileField icon={MapPin} label="Location" value={customer.location ?? "Not provided"} /><ProfileField icon={UserRound} label="Occupation" value={customer.occupation ?? "Not provided"} /></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-3"><Signal label="Intent" value={customer.currentIntent} /><Signal label="Sentiment" value={customer.currentSentiment} /><Signal label="Risk" value={customer.riskLevel} /></div>
      <section className="mt-6"><h3 className="flex items-center gap-2 text-sm font-semibold"><LockKeyhole className="size-4 text-blue-600" />KYC fields</h3>{customer.kycFields.length ? <div className="mt-3 space-y-2">{customer.kycFields.map((field) => <Card key={field.id} className="flex items-center justify-between gap-4 rounded-xl px-4 py-3 shadow-none"><span className="text-xs font-medium text-slate-500">{field.label}</span><span className="text-right text-xs font-semibold">{field.value ?? titleCase(field.status)}</span></Card>)}</div> : <p className="mt-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-500 dark:bg-slate-800/60">No KYC documents are stored. Verification is pending.</p>}</section>
      <section className="mt-6"><h3 className="flex items-center gap-2 text-sm font-semibold"><CalendarClock className="size-4 text-blue-600" />Call history</h3>{customer.previousCalls.length ? <div className="relative mt-4 space-y-4 border-l border-slate-200 pl-5 dark:border-slate-800">{customer.previousCalls.map((call) => <article key={call.id} className="relative"><span className="absolute -left-[25px] top-1 size-2 rounded-full bg-blue-600 ring-4 ring-white dark:ring-slate-950" /><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold">{titleCase(call.outcome ?? call.status)}</p><time className="text-[11px] text-slate-400">{call.date ? new Date(call.date).toLocaleDateString() : ""}</time></div><p className="mt-1 text-xs leading-5 text-slate-500">{call.summary ?? "No summary recorded"}</p></article>)}</div> : <p className="mt-3 text-xs text-slate-400">No previous calls.</p>}</section>
      <section className="mt-6 grid gap-4 sm:grid-cols-2"><Card className="p-4"><h3 className="flex items-center gap-2 text-xs font-semibold"><ShoppingBag className="size-4 text-blue-600" />Purchases</h3><div className="mt-3 space-y-2">{customer.previousPurchases.length ? customer.previousPurchases.map((purchase) => <div key={purchase.id} className="text-xs"><p className="font-medium">{purchase.product}</p><p className="text-slate-400">{purchase.currency} {purchase.amount.toLocaleString()}</p></div>) : <p className="text-xs text-slate-400">No purchases.</p>}</div></Card><Card className="p-4"><h3 className="flex items-center gap-2 text-xs font-semibold"><Tag className="size-4 text-blue-600" />Tags and signals</h3><div className="mt-3 flex flex-wrap gap-1.5">{[...customer.tags, ...customer.buyingSignals].length ? [...customer.tags, ...customer.buyingSignals].map((item) => <Badge key={item}>{titleCase(item)}</Badge>) : <p className="text-xs text-slate-400">No tags or buying signals.</p>}</div></Card></section>
      <section className="mt-4 grid gap-4 sm:grid-cols-2">
        <Card className="p-4"><h3 className="flex items-center gap-2 text-xs font-semibold"><Tag className="size-4 text-blue-600" />Past offers</h3><div className="mt-3 space-y-2">{customer.pastOffers.length ? customer.pastOffers.map((offer) => <div key={offer.id} className="flex items-start justify-between gap-3 text-xs"><div><p className="font-medium">{offer.name}</p><p className="mt-1 text-slate-400">Presented {new Date(offer.presentedAt).toLocaleDateString()}</p></div><Badge variant={offer.status === "accepted" ? "success" : "neutral"}>{titleCase(offer.status)}</Badge></div>) : <p className="text-xs text-slate-400">No offers presented.</p>}</div></Card>
        <Card className="p-4"><h3 className="flex items-center gap-2 text-xs font-semibold"><CalendarClock className="size-4 text-blue-600" />Follow-ups</h3><div className="mt-3 space-y-2">{customer.followUps.length ? customer.followUps.map((followUp) => <div key={followUp.id} className="text-xs"><div className="flex items-start justify-between gap-3"><p className="font-medium">{followUp.title}</p><Badge variant={followUp.status === "completed" ? "success" : "warning"}>{titleCase(followUp.status)}</Badge></div><p className="mt-1 text-slate-400">{new Date(followUp.scheduled_at).toLocaleString()} · {titleCase(followUp.channel)}</p></div>) : <p className="text-xs text-slate-400">No follow-ups scheduled.</p>}</div></Card>
      </section>
      <section className="mt-6"><h3 className="text-sm font-semibold">Notes and conversation history</h3>{customer.conversationHistory.length ? <div className="mt-3 space-y-2">{customer.conversationHistory.map((note) => <Card key={note.id} className="p-3"><p className="text-xs leading-5">{note.body}</p><p className="mt-2 text-[10px] text-slate-400">{titleCase(note.source)}{note.createdAt ? ` · ${new Date(note.createdAt).toLocaleString()}` : ""}</p></Card>)}</div> : <p className="mt-3 text-xs text-slate-400">No notes recorded.</p>}</section>
    </div>
  </SheetContent></Sheet>;
}

function ProfileField({ icon: Icon, label, value }: { icon: typeof Phone; label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><p className="flex items-center gap-1.5 text-[11px] font-medium text-slate-400"><Icon className="size-3.5" />{label}</p><p className="mt-1 truncate text-xs font-semibold">{value}</p></div>; }
function Signal({ label, value }: { label: string; value: string | null }) { return <div className="rounded-xl border border-slate-200 p-3 dark:border-slate-800"><p className="text-[10px] text-slate-400">{label}</p><p className="mt-1 text-xs font-semibold">{value ? titleCase(value) : "Not observed"}</p></div>; }
