"use client";

import { AlertTriangle, ArrowRight, BookOpenText, BrainCircuit, Check, CheckCircle2, CircleGauge, Copy, HeartPulse, Lightbulb, Loader2, MessageSquareText, ShieldAlert, ShieldCheck, Sparkles, Target } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import type { CopilotResult } from "@/lib/api/contracts";
import type { SocketStatus } from "@/features/copilot/use-copilot-socket";
import { cn, formatPercent, titleCase } from "@/lib/utils";

export function CopilotPanel({ result, socketStatus, socketError }: { result: CopilotResult | null; socketStatus: SocketStatus; socketError: string | null }) {
  const [copied, setCopied] = useState(false);
  if (!result) return <aside className="space-y-3" aria-label="AI Copilot"><Card className="overflow-hidden"><div className="border-b border-slate-200 px-4 py-3 dark:border-slate-800"><div className="flex items-center justify-between"><p className="flex items-center gap-2 text-sm font-semibold"><Sparkles className="size-4 text-blue-600" />AI Copilot</p><Badge variant={socketStatus === "connected" ? "success" : socketStatus === "error" ? "danger" : "warning"}>{socketStatus === "connecting" || socketStatus === "reconnecting" ? <Loader2 className="size-3 animate-spin" /> : null}{titleCase(socketStatus)}</Badge></div></div><div className="space-y-3 p-4">{socketError ? <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs leading-5 text-red-700 dark:border-red-900 dark:bg-red-950/50 dark:text-red-300">{socketError}</div> : null}<Skeleton className="h-20" /><Skeleton className="h-32" /><Skeleton className="h-24" /><p className="py-2 text-center text-xs leading-5 text-slate-400">Copilot cards appear after the first analyzed customer utterance.</p></div></Card></aside>;
  const copySuggestion = async () => { await navigator.clipboard.writeText(result.suggested_response.text); setCopied(true); toast.success("Suggested reply copied"); setTimeout(() => setCopied(false), 1500); };
  const risks = [...result.guardrail.violations.map((item) => item.message), ...result.issues.map((item) => item.message)];
  const buyingSignal = result.intent === "interested" || result.next_best_action.action === "start_application";

  return <aside className="space-y-3" aria-label="AI Copilot">
    <Card className="p-4"><div className="flex items-center justify-between"><p className="flex items-center gap-2 text-sm font-semibold"><BrainCircuit className="size-4 text-blue-600" />Live understanding</p><Badge variant="primary">{formatPercent(result.confidence)} overall</Badge></div><div className="mt-4 grid grid-cols-2 gap-2"><Signal icon={Target} label="Intent" value={titleCase(result.intent)} confidence={result.agent_confidences.intent} /><Signal icon={HeartPulse} label="Emotion" value={titleCase(result.sentiment)} confidence={result.agent_confidences.sentiment} /></div><div className="mt-3"><div className="mb-1.5 flex items-center justify-between text-[11px]"><span className="text-slate-500">Aggregate confidence</span><span className="font-semibold">{formatPercent(result.confidence)}</span></div><Progress value={result.confidence * 100} /></div></Card>
    <Card className="border-blue-200 bg-blue-50/45 p-4 dark:border-blue-900 dark:bg-blue-950/20"><div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-1.5 text-xs font-semibold text-blue-700 dark:text-blue-300"><MessageSquareText className="size-3.5" />Suggested reply</p><Badge className="mt-2" variant={result.suggested_response.requires_human_review ? "warning" : "success"}>{result.suggested_response.is_fallback ? "Safe fallback" : "Grounded"} · {formatPercent(result.suggested_response.confidence)}</Badge></div><Button variant="ghost" size="icon-sm" onClick={copySuggestion} aria-label="Copy suggested reply">{copied ? <Check /> : <Copy />}</Button></div><p className="mt-3 text-sm font-medium leading-6 text-slate-900 dark:text-slate-100">{result.suggested_response.text}</p>{result.suggested_response.citation_chunk_ids.length ? <p className="mt-3 text-[10px] leading-4 text-slate-500">Sources: {result.suggested_response.citation_chunk_ids.join(", ")}</p> : null}</Card>
    <Card className="p-4"><p className="flex items-center gap-1.5 text-xs font-semibold"><ArrowRight className="size-3.5 text-blue-600" />Next best action</p><div className="mt-3 flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{titleCase(result.next_best_action.action)}</p><p className="mt-1 text-xs leading-5 text-slate-500">{result.next_best_action.rationale}</p></div><Badge variant="primary">{formatPercent(result.next_best_action.confidence)}</Badge></div>{result.next_best_action.suggested_follow_up_date ? <p className="mt-3 rounded-lg bg-slate-50 px-3 py-2 text-xs font-medium dark:bg-slate-800">Suggested date: {result.next_best_action.suggested_follow_up_date}</p> : null}</Card>
    <Card className="p-4"><div className="flex items-center justify-between"><p className="flex items-center gap-1.5 text-xs font-semibold"><BookOpenText className="size-3.5 text-blue-600" />Relevant knowledge</p><Badge>{result.retrieved_context.length} sources</Badge></div>{result.retrieved_context.length ? <div className="mt-3 space-y-2">{result.retrieved_context.slice(0, 3).map((chunk) => <details key={chunk.chunk_id} className="group rounded-xl border border-slate-200 p-3 dark:border-slate-700"><summary className="cursor-pointer list-none text-xs font-medium"><span className="flex items-center justify-between gap-2"><span className="truncate">{chunk.title}</span><Badge>{formatPercent(chunk.relevance_score)}</Badge></span></summary><p className="mt-2 text-[11px] leading-5 text-slate-500">{chunk.text}</p><p className="mt-2 break-all text-[10px] text-slate-400">{chunk.source}{chunk.page_number ? ` · Page ${chunk.page_number}` : ""}</p></details>)}</div> : <p className="mt-3 text-xs leading-5 text-slate-400">No approved knowledge met the relevance threshold. The response is a safe fallback.</p>}</Card>
    <Card className={cn("p-4", result.guardrail.is_safe ? "border-emerald-200 dark:border-emerald-900" : "border-red-200 dark:border-red-900")}><div className="flex items-center justify-between gap-2"><p className="flex items-center gap-1.5 text-xs font-semibold">{result.guardrail.is_safe ? <ShieldCheck className="size-3.5 text-emerald-600" /> : <ShieldAlert className="size-3.5 text-red-600" />}Compliance</p><Badge variant={result.guardrail.is_safe ? "success" : "danger"}>{result.guardrail.is_safe ? "Safe" : "Review required"}</Badge></div><div className="mt-3 grid grid-cols-2 gap-2 text-[11px]"><span className="rounded-lg bg-slate-50 p-2 dark:bg-slate-800">Grounded <b className="float-right">{result.guardrail.is_grounded ? "Yes" : "No"}</b></span><span className="rounded-lg bg-slate-50 p-2 dark:bg-slate-800">Coverage <b className="float-right">{formatPercent(result.guardrail.grounding_coverage)}</b></span></div>{risks.length ? <ul className="mt-3 space-y-1.5">{risks.map((risk, index) => <li key={`${risk}-${index}`} className="flex gap-2 text-[11px] leading-4 text-red-600"><AlertTriangle className="mt-0.5 size-3 shrink-0" />{risk}</li>)}</ul> : <p className="mt-3 flex items-center gap-1.5 text-[11px] text-emerald-600"><CheckCircle2 className="size-3" />No compliance warnings detected.</p>}</Card>
    <div className="grid grid-cols-2 gap-3"><MiniInsight icon={Lightbulb} label="Buying signals" value={buyingSignal ? "Detected" : "None detected"} positive={buyingSignal} /><MiniInsight icon={AlertTriangle} label="Risk factors" value={risks.length ? `${risks.length} found` : "None"} positive={!risks.length} /><MiniInsight icon={CircleGauge} label="Talking ratio" value="Needs speaker API" /><MiniInsight icon={Sparkles} label="Objection" value={result.intent === "objection" ? "Detected" : "Not current"} positive={result.intent !== "objection"} /></div>
  </aside>;
}

function Signal({ icon: Icon, label, value, confidence }: { icon: typeof Target; label: string; value: string; confidence: number }) { return <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800/60"><p className="flex items-center gap-1.5 text-[10px] font-medium text-slate-400"><Icon className="size-3" />{label}</p><p className="mt-1 truncate text-xs font-semibold">{value}</p><p className="mt-1 text-[10px] text-slate-400">{formatPercent(confidence)} confidence</p></div>; }
function MiniInsight({ icon: Icon, label, value, positive }: { icon: typeof Target; label: string; value: string; positive?: boolean }) { return <Card className="p-3 shadow-none"><p className="flex items-center gap-1.5 text-[10px] text-slate-400"><Icon className="size-3" />{label}</p><p className={cn("mt-1 text-[11px] font-semibold", positive === true && "text-emerald-600", positive === false && "text-amber-600")}>{value}</p></Card>; }
