"""Initial schema

Revision ID: c36b74c6365a
Revises: None
Create Date: 2026-08-07 23:09:01.070333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base
import app.compliance.encryption


# revision identifiers, used by Alembic.
revision: str = 'c36b74c6365a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('websocket_connected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pii_data_encrypted', app.compliance.encryption.EncryptedString(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=True)
    op.create_table('products_offers',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('embedding', app.db.base.SafeVector(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calls',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('customer_id', app.db.base.GUID(), nullable=False),
    sa.Column('agent_session_id', app.db.base.GUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('twilio_sid', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_docs',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('customer_id', app.db.base.GUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('doc_status', sa.String(length=50), nullable=True),
    sa.Column('encrypted_doc_data', app.compliance.encryption.EncryptedString(length=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_logs',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('call_id', app.db.base.GUID(), nullable=False),
    sa.Column('customer_id', app.db.base.GUID(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('recorded_announcement_sid', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow_ups',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('call_id', app.db.base.GUID(), nullable=False),
    sa.Column('customer_id', app.db.base.GUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('call_id', app.db.base.GUID(), nullable=False),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.Column('text', app.compliance.encryption.EncryptedString(length=4096), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcripts')
    op.drop_table('follow_ups')
    op.drop_table('consent_logs')
    op.drop_table('kyc_docs')
    op.drop_table('calls')
    op.drop_table('products_offers')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
