import { useEffect, useState } from 'react'
import { clauses, customer, suggestionRules, transcriptScript } from '../mockData'
import type { Suggestion, TranscriptLine } from '../types'
import { TopBar } from '../components/TopBar'
import { TranscriptPanel } from '../components/TranscriptPanel'
import { SuggestionRail } from '../components/SuggestionRail'
import { ReferenceDrawer } from '../components/ReferenceDrawer'
export function LiveCallConsole({ onNavigate, setCallData }: { onNavigate: (p: string) => void; setCallData: (x: { consent: boolean; transcript: TranscriptLine[]; notes: string[] }) => void }) {
 const [consent, setConsent] = useState(false), [seconds, setSeconds] = useState(0), [lines, setLines] = useState<TranscriptLine[]>([]), [suggestions, setSuggestions] = useState<Suggestion[]>([]), [notes, setNotes] = useState<string[]>([]), [drawer, setDrawer] = useState(false), [highlighted, setHighlighted] = useState<string>(), [query, setQuery] = useState('')
 useEffect(() => { const id = window.setInterval(() => setSeconds(s => s + 1), 1000); return () => clearInterval(id) }, [])
 useEffect(() => { setCallData({ consent, transcript: lines, notes }) }, [consent, lines, notes, setCallData])
 useEffect(() => { if (!consent || lines.length >= transcriptScript.length) return; const timer = window.setTimeout(() => { const line = transcriptScript[lines.length]; setLines(x => [...x, line]); if (line.intent) { const rule = suggestionRules[line.intent]; setHighlighted(line.topic); setDrawer(true); setSuggestions(old => [...old.map(s => ({ ...s, status: 'archived' as const })), { id: `${line.id}-${line.intent}`, intent: line.intent!, text: rule.text, source: rule.source, confidence: rule.confidence, createdAt: Date.now(), status: 'active' }]) } }, 2800); return () => clearTimeout(timer) }, [consent, lines])
 return <div className="min-h-screen bg-slate-100 text-slate-900"><TopBar consent={consent} onConfirm={() => setConsent(true)} seconds={seconds} customer={customer} onOpenCrm={() => onNavigate(`/crm/${customer.id}`)} onEnd={() => onNavigate('/call/demo-1/wrap-up')}/><main className="mx-auto flex h-[calc(100vh-72px)] max-w-[1600px] flex-col p-4"><div className="relative grid min-h-0 flex-1 grid-cols-1 gap-4 lg:grid-cols-[minmax(0,1.55fr)_minmax(360px,.85fr)]"><div className={`contents transition duration-500 ${!consent ? 'pointer-events-none select-none blur-[3px] opacity-40' : ''}`}><TranscriptPanel lines={lines}/><div className="flex min-h-0 flex-col gap-3"><SuggestionRail suggestions={suggestions} onInsert={s => setNotes(n => n.includes(s.text) ? n : [...n, s.text])}/><aside className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Agent notes</p>{notes.length === 0 ? <p className="mt-2 text-xs text-slate-400">Use “Insert into notes” to retain guidance for this call.</p> : <ul className="mt-2 space-y-2">{notes.map((n,i) => <li key={`${n}-${i}`} className="rounded-lg bg-amber-50 p-2 text-xs leading-4 text-slate-700">{n}</li>)}</ul>}</aside></div></div>{!consent && <div className="absolute inset-0 z-10 grid place-items-center"><div className="max-w-sm rounded-2xl border border-amber-200 bg-white p-6 text-center shadow-xl"><p className="text-lg font-bold">Waiting for customer consent</p><p className="mt-2 text-sm text-slate-600">Confirm consent in the top bar before viewing or generating live call assistance.</p></div></div>}</div><ReferenceDrawer clauses={clauses} query={query} setQuery={setQuery} open={drawer} setOpen={setDrawer} highlighted={highlighted}/></main></div>
}
