import { BriefcaseBusiness, CalendarClock, LockKeyhole, Mail, MapPin, Phone, ShieldCheck, UserRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import type { CoreCustomer } from "@/lib/api/contracts";
import { getInitials, titleCase } from "@/lib/utils";

export function CustomerPanel({ customer, leadScore }: { customer: CoreCustomer; leadScore?: number }) {
  const score = leadScore ?? customer.leadScore;
  return <aside className="space-y-3" aria-label="Customer profile"><Card className="p-4"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-blue-50 text-sm font-semibold text-blue-700 dark:bg-blue-950 dark:text-blue-300">{getInitials(customer.name)}</div><div className="min-w-0"><p className="truncate text-sm font-semibold">{customer.name}</p><p className="mt-0.5 truncate text-[11px] text-slate-400">{customer.id}</p></div></div><div className="mt-4 space-y-2.5"><Detail icon={Phone} value={customer.phone} /><Detail icon={Mail} value={customer.email ?? "Email not provided"} /><Detail icon={MapPin} value={customer.location ?? "Location not provided"} /><Detail icon={BriefcaseBusiness} value={customer.occupation ?? "Occupation not provided"} /></div></Card>
    <Card className="p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold">Lead score</p><Badge variant={score >= 70 ? "success" : score >= 40 ? "warning" : "neutral"}>{score}/100</Badge></div><Progress value={score} className="mt-3" indicatorClassName={score >= 70 ? "bg-emerald-500" : "bg-blue-600"} /><p className="mt-2 text-[11px] leading-4 text-slate-400">Updated continuously from persisted copilot signals and the post-call CRM score.</p></Card>
    <Card className="p-4"><div className="flex items-center justify-between"><p className="flex items-center gap-1.5 text-xs font-semibold"><LockKeyhole className="size-3.5 text-blue-600" />KYC status</p><Badge variant={customer.kycStatus === "verified" ? "success" : "warning"}><ShieldCheck className="size-3" />{titleCase(customer.kycStatus)}</Badge></div><div className="mt-3 space-y-2">{customer.kycFields.length ? customer.kycFields.map((field) => <div key={field.id} className="flex items-center justify-between gap-2 rounded-xl bg-slate-50 px-3 py-2 dark:bg-slate-800/60"><span className="text-[11px] text-slate-500">{field.label}</span><span className="truncate text-[11px] font-medium text-slate-700 dark:text-slate-300">{field.value ?? titleCase(field.status)}</span></div>) : <p className="text-[11px] text-slate-400">No KYC records are stored.</p>}</div></Card>
    <Card className="p-4"><p className="flex items-center gap-1.5 text-xs font-semibold"><CalendarClock className="size-3.5 text-blue-600" />Recent timeline</p><div className="mt-3 space-y-3">{customer.interactions.slice(0, 3).map((interaction, index) => <div key={`${interaction.date}-${index}`} className="border-l border-slate-200 pl-3 dark:border-slate-700"><div className="flex items-center justify-between gap-2"><span className="text-[11px] font-medium">{interaction.outcome}</span><time className="text-[10px] text-slate-400">{interaction.date}</time></div><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-slate-500">{interaction.note}</p></div>)}</div></Card>
    <Card className="p-4"><p className="flex items-center gap-1.5 text-xs font-semibold"><UserRound className="size-3.5" />Live customer signals</p><div className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><Signal label="Intent" value={customer.currentIntent} /><Signal label="Sentiment" value={customer.currentSentiment} /><Signal label="Risk" value={customer.riskLevel} /><Signal label="Stage" value={customer.stage} /></div></Card>
  </aside>;
}

function Detail({ icon: Icon, value, muted = false }: { icon: typeof Phone; value: string; muted?: boolean }) { return <div className={`flex items-center gap-2 text-xs ${muted ? "text-slate-400" : "text-slate-600 dark:text-slate-300"}`}><Icon className="size-3.5 shrink-0 text-slate-400" /><span className="truncate">{value}</span></div>; }
function Signal({ label, value }: { label: string; value: string | null }) { return <div className="rounded-lg bg-slate-50 p-2 dark:bg-slate-800/60"><p className="text-slate-400">{label}</p><p className="mt-1 font-semibold">{value ? titleCase(value) : "Not observed"}</p></div>; }
