import { BriefcaseBusiness, CalendarClock, LockKeyhole, Mail, MapPin, Phone, ShieldCheck, UserRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import type { CoreCustomer } from "@/lib/api/contracts";
import { getInitials } from "@/lib/utils";

export function CustomerPanel({ customer, leadScore }: { customer: CoreCustomer; leadScore?: number }) {
  return <aside className="space-y-3" aria-label="Customer profile"><Card className="p-4"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-blue-50 text-sm font-semibold text-blue-700 dark:bg-blue-950 dark:text-blue-300">{getInitials(customer.name)}</div><div className="min-w-0"><p className="truncate text-sm font-semibold">{customer.name}</p><p className="mt-0.5 truncate text-[11px] text-slate-400">{customer.id}</p></div></div><div className="mt-4 space-y-2.5"><Detail icon={Phone} value={customer.phone} /><Detail icon={Mail} value={customer.email ?? "Email not provided"} /><Detail icon={MapPin} value={customer.city} /><Detail icon={BriefcaseBusiness} value="Occupation API unavailable" muted /></div></Card>
    <Card className="p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold">Lead score</p>{leadScore != null ? <Badge variant={leadScore >= 70 ? "success" : leadScore >= 40 ? "warning" : "neutral"}>{leadScore}/100</Badge> : <Badge>Post-call</Badge>}</div><Progress value={leadScore ?? 0} className="mt-3" indicatorClassName={leadScore != null && leadScore >= 70 ? "bg-emerald-500" : "bg-blue-600"} /><p className="mt-2 text-[11px] leading-4 text-slate-400">{leadScore == null ? "The backend calculates this only in the post-call CRM summary." : "Deterministic score from the AI CRM agent."}</p></Card>
    <Card className="p-4"><div className="flex items-center justify-between"><p className="flex items-center gap-1.5 text-xs font-semibold"><LockKeyhole className="size-3.5 text-blue-600" />KYC status</p><Badge variant="success"><ShieldCheck className="size-3" />On file</Badge></div><div className="mt-3 space-y-2">{customer.kycFields.map((field) => <div key={field.label} className="flex items-center justify-between gap-2 rounded-xl bg-slate-50 px-3 py-2 dark:bg-slate-800/60"><span className="text-[11px] text-slate-500">{field.label}</span><span className="truncate text-[11px] font-medium text-slate-700 dark:text-slate-300">{field.value}</span></div>)}</div></Card>
    <Card className="p-4"><p className="flex items-center gap-1.5 text-xs font-semibold"><CalendarClock className="size-3.5 text-blue-600" />Recent timeline</p><div className="mt-3 space-y-3">{customer.interactions.slice(0, 3).map((interaction, index) => <div key={`${interaction.date}-${index}`} className="border-l border-slate-200 pl-3 dark:border-slate-700"><div className="flex items-center justify-between gap-2"><span className="text-[11px] font-medium">{interaction.outcome}</span><time className="text-[10px] text-slate-400">{interaction.date}</time></div><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-slate-500">{interaction.note}</p></div>)}</div></Card>
    <Card className="border-dashed p-4 shadow-none"><p className="flex items-center gap-1.5 text-xs font-semibold"><UserRound className="size-3.5" />Additional profile</p><p className="mt-2 text-[11px] leading-4 text-slate-400">Purchases, EMI eligibility, tags, and complete lead history require customer profile APIs that are not available.</p></Card>
  </aside>;
}

function Detail({ icon: Icon, value, muted = false }: { icon: typeof Phone; value: string; muted?: boolean }) { return <div className={`flex items-center gap-2 text-xs ${muted ? "text-slate-400" : "text-slate-600 dark:text-slate-300"}`}><Icon className="size-3.5 shrink-0 text-slate-400" /><span className="truncate">{value}</span></div>; }
